### ISSUE TITLE
Create linear decrease in future emissions based on remaining country carbon budget

### ISSUE THREAD

**Issue by floriandierickx** [floriandierickx/emission-budgets#1]
As the application at the moment only displays historical and recent emissions, it would be nice to implement:

- A function/code/loop that calculates a linear decrease in emissions and feeds this into a series that can be plotted in the third part (`Future` data) in the graph [here](https://github.com/floriandierickx/emission-budgets/blob/4578f0b1fd0ade04d289d75fef4621d751529e51/app.py#L144) (static) and [here](https://github.com/floriandierickx/emission-budgets/blob/4578f0b1fd0ade04d289d75fef4621d751529e51/app.py#L233) (dynamic with callback), based on:
  - the country-specific carbon budget left from 2020 onwards : [link to code](https://github.com/floriandierickx/emission-budgets/blob/ffbcb24ce65d473483d3ebdcf492fc135316b984/app.py#L303)
  - years left for the country to go to zero : [link to code](https://github.com/floriandierickx/emission-budgets/blob/ffbcb24ce65d473483d3ebdcf492fc135316b984/app.py#L326).

The imported [google sheet](https://docs.google.com/spreadsheets/d/1R1U8iwlf2NdHDj6ykzgUqocQDfpbVB6i8lsStN3eNlo/edit?usp=sharing) - sheet: `import` - has per-country emission data until 2019, and empty cells until 2200.

An idea is to populate these empty cells with some code or function inside the application, linearly decreasing based on the country carbon budget and years left until emissions are depleted. The question is: how to do this?

Help is welcome!

**Comment by gschivley** [comment]
I don't have a solution, but started writing some stream-of-thought ideas below...

So you want to show a linear decrease in emissions from now until an end date (2050?) given some total budget? If that's the case we know
1. The starting annual emissions in 2020
2. The ending annual emissions in 2050 (0)
3. The number of years (30)

A linear decrease probably wouldn't match the remaining carbon budget. So it could be a non-linear decrease (solve for parameters that leave total emissions equal to budget) or could be linear and end before 2050. 

Are the figures you want to emulate always a linear decrease?

**Comment by spencermize** [comment]
I'm no expert here (but I am a climate-engaged web developer, so hopefully I can still assist?), but wouldn't we want some kind of exponential decay function if we're trying to match reality? I've been operating under the assumption that the last 20% of emissions reductions will be the most challenging and thus we'll need the most time to solve...

**Comment by floriandierickx** [comment]
Thanks both for your replies! It might be really nice to implement a decay function - based on on the assumption that later efforts will be harder, but for the sake of simplicity (I already can't figure out the linear issue :p), it feels also logical to start with a linear decrease, attributing the emission reduction effort evenly over all the years (as [evocated in the blogpost of Stefan Rahmstorf](https://hyp.is/lY4y-OOWEemHuscPfzFJTw/www.realclimate.org/index.php/archives/2019/08/how-much-co2-your-country-can-still-emit-in-three-simple-steps/)). If you have ideas on how to implement other types of decay, that would be really cool as well of course. In any of the cases (focusing on the linear issue here now), what is known is :

- The starting annual emission in 2019, at the same emission level of 2017, as is this the latest data available for all the countries that can be assumed to be fixed as 2019 is almost over. This yearly 2017(and 2018/2019)-emission data for a specific country can be taken directly from the imported dataset using `round(df_budget.loc[df_budget['country'] == selected_country, '2017'].values.flatten().tolist()[0], 2),` (see [line 299](https://github.com/floriandierickx/emission-budgets/blob/21ef1b909c20e65c9a22da714e19d46104c9270f/app.py#L299))

- The emission budget that can be used from 2016 (year of the Paris agreement) onwards. This value can be calculated from the data using (see [lines 288 to 293](https://github.com/floriandierickx/emission-budgets/blob/21ef1b909c20e65c9a22da714e19d46104c9270f/app.py#L288)
```python
round(((carbon_budget + 80)  # carbon budget country
    * df_budget.loc[df_budget['country'] == selected_country, 'total_kton_CO2'].values.flatten().tolist()[0])
    / df_budget.loc[df_budget['country'] == selected_country, 'per_capita_CO2'].values.flatten().tolist()[0]
    / global_emissions[0]
    * global_per_capita_emissions[0]
    / 1000, 2),
```
This value is calculated as:
<img width="896" alt="Screenshot 2019-09-30 at 17 53 58" src="https://user-images.githubusercontent.com/12695083/65895165-4c44c980-e3ab-11e9-85b4-fb5fd99cc875.png">

(taken from the [spreadsheet](https://docs.google.com/spreadsheets/d/1R1U8iwlf2NdHDj6ykzgUqocQDfpbVB6i8lsStN3eNlo/edit?usp=sharing) of Stefan Rahmstorf - for example cell E25 for Afghanistan in the `original` sheet. I hope I interpreted it here correctly)

- Accounting for the 2 years that have already passed (assuming constant emissions in every country until the end of 2018), the emission budget that is left to deplete from 2019 onwards needs to be reduced by two years of constant 2017/2018 emissions. This can be calculated by using the above country emission budget (see [lines 305-310](https://github.com/floriandierickx/emission-budgets/blob/472c6792fa246b28cca8886138d673409e73a518/app.py#L305)), by substracting
  ```python
  - (2 * df_budget.loc[df_budget['country'] == selected_country, '2017'].values.flatten().tolist()[0]), 2)
  ```
   in the end.

From then it is straightforward to calculate the remaining years left at constant emissions, by dividing the remaining carbon budget from 2019 onwards by a constant 2017/2018/2019 emission level (assumed to stay the same), as done in [line 316 to 322](https://github.com/floriandierickx/emission-budgets/blob/472c6792fa246b28cca8886138d673409e73a518/app.py#L316).

Now where I am stuck is how to 'force' a linear decrease to zero with as baseline this carbon budget and starting amount in 2019. It feels like a primary school math question but I can't get my head around it at the moment. I've been playing around with pythagoras, sinuses, tangent degrees etc, but didn't arrive yet :p And then is the question how to implement it in python, because there are considerable country-differences in the spread of this in time (sometimes reaching 300 years for some countries). At the moment I created empty cells for every country until 2200 in the imported dataset, but this might need to be go further in the future for some countries.

**Comment by gschivley** [comment]
One easy method: 
- Pick a year that it needs to hit 0 by (e.g. 2045/2050) and divide existing emissions by the number of years until then. 
- Subtract that amount each year to get a linear decrease. 
- Sum the emissions and see if it's less than the remaining budget.
- If total > budget, try an earlier year.

**Comment by floriandierickx** [comment]
@gschivley, thanks for the idea! I hope to have time to look back into it in around a month. It looks like a good python-loop excercise :p

**Comment by floriandierickx** [comment]
I couldn't keep my fingers off, it's working! (https://emission-budgets.herokuapp.com/) :) Thanks all for your suggestion, I created a function that calculates the remaining budget, and then created a list that fills up until the budget is depleted. I've put some information on how the calculation works at https://github.com/floriandierickx/emission-budgets#detailed-information-on-calculations. Feel free to suggest/implement other types of budget calculations or decrease functions, translations, ... I like the 'linear Paris agreement one' because of it's simplicity and focus on short-term goals, but it would be nice to split the information by sectors, realistically, ... so it becomes more usable. 

I like a lot a related application, https://futur.eco/ (at the moment only in French), designed to give people insight in the link between daily consumption and different carbon budgets. Maybe it can be integrated at some point..
